export const ICON_LOADING_CIRCLE = 'svg-spinners:180-ring-with-bg'
export const ICON_EMPTY = 'tabler:table-alias'
export const ICON_CLOSE = 'ep:close'
export const ICON_RELOAD = 'tabler:reload'
export const ICON_CONFIGURATION = 'icon-park-outline:database-config'
